"""empty message

Revision ID: 5128a29d830f
Revises: 
Create Date: 2025-01-15 16:37:22.819640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5128a29d830f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('trailer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediastation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_urls', sqlite.JSON(), nullable=True),
    sa.Column('path_to_exec', sa.Text(), nullable=True),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_association',
    sa.Column('mediastation_id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['mediastation_id'], ['mediastation.id'], ),
    sa.PrimaryKeyConstraint('mediastation_id', 'interaction_id')
    )
    op.create_table('media_type_association',
    sa.Column('mediastation_id', sa.Integer(), nullable=False),
    sa.Column('media_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_type.id'], ),
    sa.ForeignKeyConstraint(['mediastation_id'], ['mediastation.id'], ),
    sa.PrimaryKeyConstraint('mediastation_id', 'media_type_id')
    )
    op.create_table('visualization_association',
    sa.Column('mediastation_id', sa.Integer(), nullable=False),
    sa.Column('visualization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mediastation_id'], ['mediastation.id'], ),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualization.id'], ),
    sa.PrimaryKeyConstraint('mediastation_id', 'visualization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualization_association')
    op.drop_table('media_type_association')
    op.drop_table('interaction_association')
    op.drop_table('mediastation')
    op.drop_table('visualization')
    op.drop_table('media_type')
    op.drop_table('interaction')
    op.drop_table('exhibition')
    # ### end Alembic commands ###
